= Commons Core

This library provides collection of patterns and utilities for Scala to solve common problems.
The code was created with the aim of simplifying the development of SOA projects.

Download new versions from the Git repository https://github.com/OpaliaSystems/opalia-commons-core.

=== Packages

* codec: conversion for ACSII based codes like Base64, Hex, Radix62, ...
* concurrent: helper for concurrent bootstrapping and shutdown procedures
* cursor: a general purpose cursor implementation
* database: pattern for generic database access
* identifier: ID implementations (Object-ID, UUID)
* logging: logging facade with call-by-name message evaluation
* scripting: an API for scripting based on ideas of GraalVM
* vfs: pattern to implement a virtual file system
* worker: facade to hide various implementations of distributed computing solutions
* utility/io: methods for recursive file operations and for working with zip archives
* utility/json: helpers for working with JSON
* utility/mathx: some helper functions for mathematics
* utility/rendering: pattern for rendering objects to strings or byte sequences
* utility/string: some improvements for the string class

=== Usage

[source,scala]
----
libraryDependencies += "systems.opalia" %% "opalia-commons-core" % "<VERSION>"
----

=== License

Copyright (c) 2022 Eric Löffler (brettaufheber)

Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License.
You may obtain a copy of the License at

_http://www.apache.org/licenses/LICENSE-2.0_

Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and limitations under the License.
