= commons-core

This library is a collection of patterns and utilities for Scala to solve common problems.
It provides some code patterns for developing projects with a service-oriented architecture (SOA) and helps to build a system as a collection of loosely coupled services, what makes it easy to change or replace services without affecting the rest of the system.

Download new versions from the Git repository: https://github.com/OpaliaSystems/opalia-commons-core

== Packages

* codec: conversion for ASCII based codes like Base64, Hex, Radix62, ...
* concurrent: helper for concurrent bootstrapping and shutdown procedures
* cursor: a general purpose cursor implementation
* database: a pattern for generic database access
* identifier: some ID implementations (Object-ID, UUID)
* logging: logging facade with call-by-name message evaluation
* scripting: an API for scripting based on ideas of GraalVM
* vfs: a pattern for virtual file system
* worker: a facade to hide various implementations of distributed computing solutions
* utility/io: methods for recursive file operations and for working with zip archives; methods for parsing properties
* utility/json: helpers for working with JSON
* utility/lang: solutions to handle problems not covered by the standard library
* utility/mathx: some helper functions for mathematics
* utility/rendering: a pattern for rendering objects to strings or byte sequences
* utility/string: some improvements for the string class
* utility/time: a more relaxed parser and implicit conversions for working with the Java time library

== Usage

[source,scala]
----
libraryDependencies += "systems.opalia" %% "opalia-commons-core" % "<VERSION>"
----

== License

Copyright (c) 2022 Eric Löffler (brettaufheber)

Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License.
You may obtain a copy of the License at

_http://www.apache.org/licenses/LICENSE-2.0_

Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and limitations under the License.
